### ISSUE TITLE
Cannot invoke "java.util.List.stream()" error while running the generate allure report command

### ISSUE THREAD

**Issue by karthikeyanalaguraja** [dailymotion/allure-go#47]
I ran the  allure generate allure-results --clean -o allure-report command, but getting the below error

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "io.qameta.allure.util.ConvertUtils.convertList(java.util.Collection, java.util.function.Function)" is null
        at io.qameta.allure.allure2.Allure2Plugin.getBefore(Allure2Plugin.java:297)
        at io.qameta.allure.allure2.Allure2Plugin.lambda$convert$2(Allure2Plugin.java:144)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at io.qameta.allure.allure2.Allure2Plugin.getStages(Allure2Plugin.java:291)
        at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:144)
        at io.qameta.allure.allure2.Allure2Plugin.lambda$readResults$0(Allure2Plugin.java:111)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:111)
        at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
        at io.qameta.allure.Commands.generate(Commands.java:102)
        at io.qameta.allure.CommandLine.run(CommandLine.java:160)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.qameta.allure.CommandLine.main(CommandLine.java:92)

**Comment by karthikeyanalaguraja** [comment]
This is a blocker for me, this is not generating any report, please help

**Comment by MaximeBellou** [comment]
Hello @karthikeyanalaguraja . I cannot reproduce, we would need the content of your allure-results folder to find out which value is provided as null in one of the files. Once found, we will need to ask you how you used the library to initialise the object causing the issue.
